package:
  name: ipython-cluster-helper
  version: 0.2.15

source:
  fn: ipython-cluster-helper-0.2.15.tar.gz
  url: https://pypi.python.org/packages/source/i/ipython-cluster-helper/ipython-cluster-helper-0.2.15.tar.gz
  md5: e7bb48027733dec5c01b87019ce1e111

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - ipython
    - pyzmq

test:
  imports:
    - cluster_helper.cluster

about:
  home: https://github.com/roryk/ipython-cluster-helper
  license: MIT