package:
  name: ipython-cluster-helper
  version: 0.2.7

source:
  fn: ipython-cluster-helper-0.2.7.tar.gz
  url: https://pypi.python.org/packages/source/i/ipython-cluster-helper/ipython-cluster-helper-0.2.7.tar.gz
  md5: 7d9bc01feeeeb6613007d8f858a152fe

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - ipython
    - pyzmq

test:
  imports:
    - cluster_helper.cluster

about:
  home: https://github.com/roryk/ipython-cluster-helper
  license: MIT